### ISSUE TITLE
Question: Why call it boxed!()?

### ISSUE THREAD

**Issue by SebastianJL** [GrayJack/sugars#8]
I just wanted to ask why you called the macro for boxes `boxed!()` instead of `box!()` which would be shorter and in line with the namings of the other smart pointer macros.
Thanks for this awsome crate :)

**Comment by bohdloss** [comment]
Hello, it's because `box` is a reserved keyword in rust I'm pretty sure

**Comment by SebastianJL** [comment]
Ah yes you are right. As mentioned in the [reference](https://doc.rust-lang.org/reference/keywords.html#reserved-keywords) it is a reserved keyword

> [Reserved keywords](https://doc.rust-lang.org/reference/keywords.html#reserved-keywords)
> These keywords aren't used yet, but they are reserved for future use. They have the same restrictions as strict keywords. The reasoning behind this is to make current programs forward compatible with future versions of Rust by forbidding them to use these keywords.
> 
> Lexer
> KW_ABSTRACT : abstract
> KW_BECOME : become
> KW_BOX : box
> KW_DO : do
> KW_FINAL : final
> KW_MACRO : macro
> KW_OVERRIDE : override
> KW_PRIV : priv
> KW_TYPEOF : typeof
> KW_UNSIZED : unsized
> KW_VIRTUAL : virtual
> KW_YIELD : yield
